name: C++ GoogleTest CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y cmake g++ make

    - name: Configure with CMake
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build

    - name: Run Google Tests
      run: ctest --test-dir build
