# GitHub Actions CI/CD config
name: Build & Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install cmake libssl-dev qt6-base-dev
    - name: Build project
      run: cmake . && make
    - name: Run tests
      run: ./test/tic_tests
